title: Unexplained
author: Lou Touyarou
email: loutouyarou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Unexplained is a media dedicated to diversity in arts and culture and to give a voice to talented artists. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
